name: Build Docker image
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Projects/rocket-api
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .
