name: Build Docker image
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .
        env:
          DOCKER_BUILDKIT: 1
