name: Build and test project
on: [push]
jobs:
  test_project:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Install swiftenv
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          echo "::set-env name=PATH::$SWIFTENV_ROOT/bin:$PATH"
      - name: Install Swift
        run: swiftenv install
      - name: Build and test
        run: swiftenv exec swift test
