name: Build and test project
on: [push]
jobs:
  test-project:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:8.0
        ports:
          - '3306:3306'
        env:
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
          MYSQL_DATABASE: vapor_database
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-v2-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-v2
      - uses: actions/cache@v2
        with:
          path: ~/.swiftenv
          key: ${{ runner.os }}-swift-toolchain-${{ hashFiles('.swift-version') }}
      - name: Install swiftenv
        run: |
          [ -d ~/.swiftenv ] || git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          echo "$SWIFTENV_ROOT/bin" >> $GITHUB_PATH
      - name: Install Swift
        run: swiftenv install
      - name: Build and test
        run: swiftenv exec swift test
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SNS_PLATFORM_APPLICATION_ARN: ${{ secrets.SNS_PLATFORM_APPLICATION_ARN }}
          DATABASE_URL: mysql://vapor_username:vapor_password@0.0.0.0/vapor_database
          AUTH0_DOMAIN: https://dev-eef7o1id.us.auth0.com
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_MANAGEMENT_API_TOKEN: ${{ secrets.AUTH0_MANAGEMENT_API_TOKEN }}

      # - name: Debug
      #   if: ${{ always() }}
      #   uses: mxschmitt/action-tmate@v3
      #   env:
      #     AWS_REGION: ap-northeast-1
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     CONGNITO_IDP_USER_POOL_ID: ${{ secrets.CONGNITO_IDP_USER_POOL_ID }}
      #     CONGNITO_IDP_CLIENT_ID: ${{ secrets.CONGNITO_IDP_CLIENT_ID }}
      #     SNS_PLATFORM_APPLICATION_ARN: ${{ secrets.SNS_PLATFORM_APPLICATION_ARN }}
      #     DATABASE_URL: mysql://vapor_username:vapor_password@0.0.0.0/vapor_database
