name: Build and test project
on: [push]
jobs:
  test_project:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        ports:
          - '3306:3306'
        env:
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
          MYSQL_DATABASE: vapor_database
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Install swiftenv
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          echo "$SWIFTENV_ROOT/bin" >> $GITHUB_PATH
      - name: Install Swift
        run: swiftenv install
      - name: Build and test
        run: swiftenv exec swift test --enable-test-discovery
